/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdlc;

import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author frche1699
 */
public class Notes extends javax.swing.JPanel {

    private String[] topics, texts;

    /**
     * Creates new form Notes
     */
    public Notes(String[] topics, String[] texts) {
        initComponents();
        txtNotes.setContentType("text/html");
        //txtNotes.setEditable(false);

        this.topics = topics;
        this.texts = texts;
        //Arrays.stream(texts).forEach(System.out::println);
        generateAndDisplay();
    }

    private void generateAndDisplay() {

        String s = "<html>";

        // table of contents
        s += "<h1>Project Management Notes</h1><h2>Table of Contents</h2><ul style=\"list-style-type:square;\">";
        for (int i = 0; i < topics.length; i++) {
            s += "<li>" + "<a href='#" + "anchor" + i + "'><h4>" + topics[i] + "</h4></a>" + "</li>";
        }
        s += "</ul><p></p>";
        // content
        for (int i = 0; i < texts.length; i++) {
            s += "<h3><a name='" + "anchor" + i + "'>" + topics[i] + "</a></h3>";
            s += "<p>" + texts[i] + "</p>";
            s += "<p></p><p></p>";
        }

        s += "</html>";
        //System.out.println(s);
        txtNotes.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JEditorPane();
        txtNotes.setEditable(false);
        txtNotes.addHyperlinkListener(new HyperlinkListener() {
            @Override
            public void hyperlinkUpdate(final HyperlinkEvent pE) {
                if (HyperlinkEvent.EventType.ACTIVATED == pE.getEventType()) {
                    //System.out.println("JEditorPane link click: url='" + pE.getURL() + "' description='" + pE.getDescription() + "'");
                    String reference = pE.getDescription();
                    if (reference != null && reference.startsWith("#")) { // link must start with # to be internal reference
                        reference = reference.substring(1);
                        txtNotes.scrollToReference(reference);
                        //txtNotes.scrollToReference("#" + reference);
                        //System.out.println("scrolled");
                    }
                }
            }
        });
        btnBack = new javax.swing.JButton();

        jScrollPane2.setViewportView(txtNotes);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        SDLC.setMainContentPane(new Welcome());
        SDLC.setResizable(false);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane txtNotes;
    // End of variables declaration//GEN-END:variables
}
